# Generated by Django 4.2.16 on 2026-04-26 21:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cat',
            unique_together={('name', 'owner')},
        ),
    ]
